INSERT INTO clientes(id, nombre,apellido,email,create_at,foto) VALUES(1,'Oscar','Cervantes','ocervantes@gmail.com','2023-05-01','');
INSERT INTO clientes(id, nombre,apellido,email,create_at,foto) VALUES(2,'Jesus','Cervantes','JC@gmail.com','2022-03-23','');
INSERT INTO clientes(id, nombre,apellido,email,create_at,foto) VALUES(3,'guadalupe','perez','gp@gmail.com','2023-05-01','');
INSERT INTO clientes(id, nombre,apellido,email,create_at,foto) VALUES(4,'maria','torres','mt@gmail.com','2023-05-01','');
INSERT INTO clientes(id, nombre,apellido,email,create_at,foto) VALUES(5,'diana','liz','dl@gmail.com','2023-05-01','');
INSERT INTO clientes(id, nombre,apellido,email,create_at,foto) VALUES(6,'carolina','llano','cl@gmail.com','2023-05-01','');
INSERT INTO clientes(id, nombre,apellido,email,create_at,foto) VALUES(7,'iris','torrez','it@gmail.com','2023-05-01','');
INSERT INTO clientes(id, nombre,apellido,email,create_at,foto) VALUES(8,'carlos','barona','cb@gmail.com','2023-05-01','');
INSERT INTO clientes(id, nombre,apellido,email,create_at,foto) VALUES(9,'pepe','garcia','pg@gmail.com','2023-05-01','');
INSERT INTO clientes(id, nombre,apellido,email,create_at,foto) VALUES(10,'jose','garcia','jg@gmail.com','2023-05-01','');
INSERT INTO clientes(id, nombre,apellido,email,create_at,foto) VALUES(11,'juan','torrez','jt@gmail.com','2023-05-01','');
INSERT INTO clientes(id, nombre,apellido,email,create_at,foto) VALUES(12,'carlos','liz','cl@gmail.com','2023-05-01','');
INSERT INTO clientes(id, nombre,apellido,email,create_at,foto) VALUES(13,'brian','has','bh@gmail.com','2023-05-01','');

INSERT INTO productos(nombre,precio,create_at) VALUES('Panasonic Pantalla LCD',9990,NOW());
INSERT INTO productos(nombre,precio,create_at) VALUES('Sony Camara digital',3125,NOW());
INSERT INTO productos(nombre,precio,create_at) VALUES('Apple iPod shuffle',2990,NOW());
INSERT INTO productos(nombre,precio,create_at) VALUES('Sonic Notebook Z110',3490,NOW());
INSERT INTO productos(nombre,precio,create_at) VALUES('Hewlett pack',56990,NOW());
INSERT INTO productos(nombre,precio,create_at) VALUES('Mica Comoda 5 cajones',59990,NOW());